# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto.article import article_pb2 as article_dot_article__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class ArticleServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTopicArticles = channel.unary_unary(
                '/ArticleService/GetTopicArticles',
                request_serializer=article_dot_article__pb2.GetTopicArticlesRequest.SerializeToString,
                response_deserializer=article_dot_article__pb2.TopicArticles.FromString,
                )
        self.SetTopicArticles = channel.unary_unary(
                '/ArticleService/SetTopicArticles',
                request_serializer=article_dot_article__pb2.SetTopicArticlesRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class ArticleServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTopicArticles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTopicArticles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArticleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTopicArticles': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopicArticles,
                    request_deserializer=article_dot_article__pb2.GetTopicArticlesRequest.FromString,
                    response_serializer=article_dot_article__pb2.TopicArticles.SerializeToString,
            ),
            'SetTopicArticles': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTopicArticles,
                    request_deserializer=article_dot_article__pb2.SetTopicArticlesRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ArticleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ArticleService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTopicArticles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ArticleService/GetTopicArticles',
            article_dot_article__pb2.GetTopicArticlesRequest.SerializeToString,
            article_dot_article__pb2.TopicArticles.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetTopicArticles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ArticleService/SetTopicArticles',
            article_dot_article__pb2.SetTopicArticlesRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
