# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: article/article.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x61rticle/article.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8a\x01\n\rTopicArticles\x12\x38\n\rtopicArticles\x18\x01 \x03(\x0b\x32!.TopicArticles.TopicArticlesEntry\x1a?\n\x12TopicArticlesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x18\n\x05value\x18\x02 \x01(\x0b\x32\t.Articles:\x02\x38\x01\"&\n\x08\x41rticles\x12\x1a\n\x08\x61rticles\x18\x01 \x03(\x0b\x32\x08.Article\"\x86\x01\n\x07\x41rticle\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\x12\x10\n\x08imageUrl\x18\x04 \x01(\t\x12\x0e\n\x06source\x18\x05 \x01(\t\x12(\n\x04\x64\x61te\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x1c\n\nTopicNames\x12\x0e\n\x06topics\x18\x01 \x03(\t2\xf1\x01\n\x0e\x41rticleService\x12/\n\x10GetTopicArticles\x12\x0b.TopicNames\x1a\x0e.TopicArticles\x12:\n\x10SetTopicArticles\x12\x0e.TopicArticles\x1a\x16.google.protobuf.Empty\x12\x38\n\x13GetTrendingArticles\x12\x16.google.protobuf.Empty\x1a\t.Articles\x12\x38\n\x13SetTrendingArticles\x12\t.Articles\x1a\x16.google.protobuf.EmptyB\x0fZ\rproto/articleb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'article.article_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\rproto/article'
  _globals['_TOPICARTICLES_TOPICARTICLESENTRY']._options = None
  _globals['_TOPICARTICLES_TOPICARTICLESENTRY']._serialized_options = b'8\001'
  _globals['_TOPICARTICLES']._serialized_start=88
  _globals['_TOPICARTICLES']._serialized_end=226
  _globals['_TOPICARTICLES_TOPICARTICLESENTRY']._serialized_start=163
  _globals['_TOPICARTICLES_TOPICARTICLESENTRY']._serialized_end=226
  _globals['_ARTICLES']._serialized_start=228
  _globals['_ARTICLES']._serialized_end=266
  _globals['_ARTICLE']._serialized_start=269
  _globals['_ARTICLE']._serialized_end=403
  _globals['_TOPICNAMES']._serialized_start=405
  _globals['_TOPICNAMES']._serialized_end=433
  _globals['_ARTICLESERVICE']._serialized_start=436
  _globals['_ARTICLESERVICE']._serialized_end=677
# @@protoc_insertion_point(module_scope)
