# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from proto.interest import interest_pb2 as interest_dot_interest__pb2


class InterestServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddInterests = channel.unary_unary(
                '/InterestService/AddInterests',
                request_serializer=interest_dot_interest__pb2.AddInterestsRequest.SerializeToString,
                response_deserializer=interest_dot_interest__pb2.InterestResponse.FromString,
                )
        self.DeleteInterests = channel.unary_unary(
                '/InterestService/DeleteInterests',
                request_serializer=interest_dot_interest__pb2.DeleteInterestsRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetInterests = channel.unary_unary(
                '/InterestService/GetInterests',
                request_serializer=interest_dot_interest__pb2.GetInterestsRequest.SerializeToString,
                response_deserializer=interest_dot_interest__pb2.InterestResponse.FromString,
                )


class InterestServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddInterests(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteInterests(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInterests(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InterestServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddInterests': grpc.unary_unary_rpc_method_handler(
                    servicer.AddInterests,
                    request_deserializer=interest_dot_interest__pb2.AddInterestsRequest.FromString,
                    response_serializer=interest_dot_interest__pb2.InterestResponse.SerializeToString,
            ),
            'DeleteInterests': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteInterests,
                    request_deserializer=interest_dot_interest__pb2.DeleteInterestsRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetInterests': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInterests,
                    request_deserializer=interest_dot_interest__pb2.GetInterestsRequest.FromString,
                    response_serializer=interest_dot_interest__pb2.InterestResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'InterestService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class InterestService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddInterests(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/InterestService/AddInterests',
            interest_dot_interest__pb2.AddInterestsRequest.SerializeToString,
            interest_dot_interest__pb2.InterestResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteInterests(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/InterestService/DeleteInterests',
            interest_dot_interest__pb2.DeleteInterestsRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetInterests(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/InterestService/GetInterests',
            interest_dot_interest__pb2.GetInterestsRequest.SerializeToString,
            interest_dot_interest__pb2.InterestResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
