/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.12.4
// source: proto/interest/interest.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js')
const proto = require('./interest_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.InterestServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.InterestServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.AddInterestsRequest,
 *   !proto.InterestResponse>}
 */
const methodDescriptor_InterestService_AddInterests = new grpc.web.MethodDescriptor(
  '/InterestService/AddInterests',
  grpc.web.MethodType.UNARY,
  proto.AddInterestsRequest,
  proto.InterestResponse,
  /**
   * @param {!proto.AddInterestsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.InterestResponse.deserializeBinary
);


/**
 * @param {!proto.AddInterestsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.InterestResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.InterestResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.InterestServiceClient.prototype.addInterests =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/InterestService/AddInterests',
      request,
      metadata || {},
      methodDescriptor_InterestService_AddInterests,
      callback);
};


/**
 * @param {!proto.AddInterestsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.InterestResponse>}
 *     Promise that resolves to the response
 */
proto.InterestServicePromiseClient.prototype.addInterests =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/InterestService/AddInterests',
      request,
      metadata || {},
      methodDescriptor_InterestService_AddInterests);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.DeleteInterestsRequest,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_InterestService_DeleteInterests = new grpc.web.MethodDescriptor(
  '/InterestService/DeleteInterests',
  grpc.web.MethodType.UNARY,
  proto.DeleteInterestsRequest,
  google_protobuf_empty_pb.Empty,
  /**
   * @param {!proto.DeleteInterestsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.DeleteInterestsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.InterestServiceClient.prototype.deleteInterests =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/InterestService/DeleteInterests',
      request,
      metadata || {},
      methodDescriptor_InterestService_DeleteInterests,
      callback);
};


/**
 * @param {!proto.DeleteInterestsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.InterestServicePromiseClient.prototype.deleteInterests =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/InterestService/DeleteInterests',
      request,
      metadata || {},
      methodDescriptor_InterestService_DeleteInterests);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.GetInterestsRequest,
 *   !proto.InterestResponse>}
 */
const methodDescriptor_InterestService_GetInterests = new grpc.web.MethodDescriptor(
  '/InterestService/GetInterests',
  grpc.web.MethodType.UNARY,
  proto.GetInterestsRequest,
  proto.InterestResponse,
  /**
   * @param {!proto.GetInterestsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.InterestResponse.deserializeBinary
);


/**
 * @param {!proto.GetInterestsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.InterestResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.InterestResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.InterestServiceClient.prototype.getInterests =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/InterestService/GetInterests',
      request,
      metadata || {},
      methodDescriptor_InterestService_GetInterests,
      callback);
};


/**
 * @param {!proto.GetInterestsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.InterestResponse>}
 *     Promise that resolves to the response
 */
proto.InterestServicePromiseClient.prototype.getInterests =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/InterestService/GetInterests',
      request,
      metadata || {},
      methodDescriptor_InterestService_GetInterests);
};


module.exports = proto;

