# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: topic/topic.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11topic/topic.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x15\n\x05Topic\x12\x0c\n\x04name\x18\x01 \x01(\t\"\'\n\rTopicResponse\x12\x16\n\x06topics\x18\x01 \x03(\x0b\x32\x06.Topic\"\"\n\x10GetTopicsRequest\x12\x0e\n\x06userId\x18\x01 \x01(\x04\":\n\x10\x41\x64\x64TopicsRequest\x12\x16\n\x06topics\x18\x01 \x03(\x0b\x32\x06.Topic\x12\x0e\n\x06userId\x18\x02 \x01(\x04\"9\n\x13RemoveTopicsRequest\x12\x12\n\ntopicNames\x18\x01 \x03(\t\x12\x0e\n\x06userId\x18\x02 \x01(\x04\x32\xac\x01\n\x0cTopicService\x12.\n\tAddTopics\x12\x11.AddTopicsRequest\x1a\x0e.TopicResponse\x12.\n\tGetTopics\x12\x11.GetTopicsRequest\x1a\x0e.TopicResponse\x12<\n\x0cRemoveTopics\x12\x14.RemoveTopicsRequest\x1a\x16.google.protobuf.EmptyB\rZ\x0bproto/topicb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'topic.topic_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\013proto/topic'
  _TOPIC._serialized_start=50
  _TOPIC._serialized_end=71
  _TOPICRESPONSE._serialized_start=73
  _TOPICRESPONSE._serialized_end=112
  _GETTOPICSREQUEST._serialized_start=114
  _GETTOPICSREQUEST._serialized_end=148
  _ADDTOPICSREQUEST._serialized_start=150
  _ADDTOPICSREQUEST._serialized_end=208
  _REMOVETOPICSREQUEST._serialized_start=210
  _REMOVETOPICSREQUEST._serialized_end=267
  _TOPICSERVICE._serialized_start=270
  _TOPICSERVICE._serialized_end=442
# @@protoc_insertion_point(module_scope)
