/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.12.4
// source: proto/article/article.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as proto_article_article_pb from './article_pb';
import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb';


export class ArticleServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetArticles = new grpcWeb.MethodDescriptor(
    '/ArticleService/GetArticles',
    grpcWeb.MethodType.UNARY,
    proto_article_article_pb.User,
    proto_article_article_pb.UserArticles,
    (request: proto_article_article_pb.User) => {
      return request.serializeBinary();
    },
    proto_article_article_pb.UserArticles.deserializeBinary
  );

  getArticles(
    request: proto_article_article_pb.User,
    metadata: grpcWeb.Metadata | null): Promise<proto_article_article_pb.UserArticles>;

  getArticles(
    request: proto_article_article_pb.User,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: proto_article_article_pb.UserArticles) => void): grpcWeb.ClientReadableStream<proto_article_article_pb.UserArticles>;

  getArticles(
    request: proto_article_article_pb.User,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: proto_article_article_pb.UserArticles) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ArticleService/GetArticles',
        request,
        metadata || {},
        this.methodDescriptorGetArticles,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ArticleService/GetArticles',
    request,
    metadata || {},
    this.methodDescriptorGetArticles);
  }

  methodDescriptorSetUserArticles = new grpcWeb.MethodDescriptor(
    '/ArticleService/SetUserArticles',
    grpcWeb.MethodType.UNARY,
    proto_article_article_pb.UserArticles,
    google_protobuf_empty_pb.Empty,
    (request: proto_article_article_pb.UserArticles) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  setUserArticles(
    request: proto_article_article_pb.UserArticles,
    metadata: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  setUserArticles(
    request: proto_article_article_pb.UserArticles,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  setUserArticles(
    request: proto_article_article_pb.UserArticles,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/ArticleService/SetUserArticles',
        request,
        metadata || {},
        this.methodDescriptorSetUserArticles,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/ArticleService/SetUserArticles',
    request,
    metadata || {},
    this.methodDescriptorSetUserArticles);
  }

}

