/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.12.4
// source: proto/article/article.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js')
const proto = require('./article_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ArticleServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ArticleServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.User,
 *   !proto.UserArticles>}
 */
const methodDescriptor_ArticleService_GetArticles = new grpc.web.MethodDescriptor(
  '/ArticleService/GetArticles',
  grpc.web.MethodType.UNARY,
  proto.User,
  proto.UserArticles,
  /**
   * @param {!proto.User} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.UserArticles.deserializeBinary
);


/**
 * @param {!proto.User} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.UserArticles)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.UserArticles>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ArticleServiceClient.prototype.getArticles =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ArticleService/GetArticles',
      request,
      metadata || {},
      methodDescriptor_ArticleService_GetArticles,
      callback);
};


/**
 * @param {!proto.User} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.UserArticles>}
 *     Promise that resolves to the response
 */
proto.ArticleServicePromiseClient.prototype.getArticles =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ArticleService/GetArticles',
      request,
      metadata || {},
      methodDescriptor_ArticleService_GetArticles);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.UserArticles,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_ArticleService_SetUserArticles = new grpc.web.MethodDescriptor(
  '/ArticleService/SetUserArticles',
  grpc.web.MethodType.UNARY,
  proto.UserArticles,
  google_protobuf_empty_pb.Empty,
  /**
   * @param {!proto.UserArticles} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.UserArticles} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ArticleServiceClient.prototype.setUserArticles =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ArticleService/SetUserArticles',
      request,
      metadata || {},
      methodDescriptor_ArticleService_SetUserArticles,
      callback);
};


/**
 * @param {!proto.UserArticles} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.ArticleServicePromiseClient.prototype.setUserArticles =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ArticleService/SetUserArticles',
      request,
      metadata || {},
      methodDescriptor_ArticleService_SetUserArticles);
};


module.exports = proto;

