// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/article/article.proto

package article

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ArticleServiceClient is the client API for ArticleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArticleServiceClient interface {
	GetTopicArticles(ctx context.Context, in *TopicNames, opts ...grpc.CallOption) (*TopicArticles, error)
	SetTopicArticles(ctx context.Context, in *TopicArticles, opts ...grpc.CallOption) (*empty.Empty, error)
	GetTrendingArticles(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Articles, error)
	SetTrendingArticles(ctx context.Context, in *Articles, opts ...grpc.CallOption) (*empty.Empty, error)
}

type articleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArticleServiceClient(cc grpc.ClientConnInterface) ArticleServiceClient {
	return &articleServiceClient{cc}
}

func (c *articleServiceClient) GetTopicArticles(ctx context.Context, in *TopicNames, opts ...grpc.CallOption) (*TopicArticles, error) {
	out := new(TopicArticles)
	err := c.cc.Invoke(ctx, "/ArticleService/GetTopicArticles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleServiceClient) SetTopicArticles(ctx context.Context, in *TopicArticles, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/ArticleService/SetTopicArticles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleServiceClient) GetTrendingArticles(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Articles, error) {
	out := new(Articles)
	err := c.cc.Invoke(ctx, "/ArticleService/GetTrendingArticles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleServiceClient) SetTrendingArticles(ctx context.Context, in *Articles, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/ArticleService/SetTrendingArticles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArticleServiceServer is the server API for ArticleService service.
// All implementations must embed UnimplementedArticleServiceServer
// for forward compatibility
type ArticleServiceServer interface {
	GetTopicArticles(context.Context, *TopicNames) (*TopicArticles, error)
	SetTopicArticles(context.Context, *TopicArticles) (*empty.Empty, error)
	GetTrendingArticles(context.Context, *empty.Empty) (*Articles, error)
	SetTrendingArticles(context.Context, *Articles) (*empty.Empty, error)
	mustEmbedUnimplementedArticleServiceServer()
}

// UnimplementedArticleServiceServer must be embedded to have forward compatible implementations.
type UnimplementedArticleServiceServer struct {
}

func (UnimplementedArticleServiceServer) GetTopicArticles(context.Context, *TopicNames) (*TopicArticles, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopicArticles not implemented")
}
func (UnimplementedArticleServiceServer) SetTopicArticles(context.Context, *TopicArticles) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTopicArticles not implemented")
}
func (UnimplementedArticleServiceServer) GetTrendingArticles(context.Context, *empty.Empty) (*Articles, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrendingArticles not implemented")
}
func (UnimplementedArticleServiceServer) SetTrendingArticles(context.Context, *Articles) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTrendingArticles not implemented")
}
func (UnimplementedArticleServiceServer) mustEmbedUnimplementedArticleServiceServer() {}

// UnsafeArticleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArticleServiceServer will
// result in compilation errors.
type UnsafeArticleServiceServer interface {
	mustEmbedUnimplementedArticleServiceServer()
}

func RegisterArticleServiceServer(s grpc.ServiceRegistrar, srv ArticleServiceServer) {
	s.RegisterService(&ArticleService_ServiceDesc, srv)
}

func _ArticleService_GetTopicArticles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopicNames)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).GetTopicArticles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ArticleService/GetTopicArticles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).GetTopicArticles(ctx, req.(*TopicNames))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleService_SetTopicArticles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopicArticles)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).SetTopicArticles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ArticleService/SetTopicArticles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).SetTopicArticles(ctx, req.(*TopicArticles))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleService_GetTrendingArticles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).GetTrendingArticles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ArticleService/GetTrendingArticles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).GetTrendingArticles(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleService_SetTrendingArticles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Articles)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).SetTrendingArticles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ArticleService/SetTrendingArticles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).SetTrendingArticles(ctx, req.(*Articles))
	}
	return interceptor(ctx, in, info, handler)
}

// ArticleService_ServiceDesc is the grpc.ServiceDesc for ArticleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArticleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ArticleService",
	HandlerType: (*ArticleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTopicArticles",
			Handler:    _ArticleService_GetTopicArticles_Handler,
		},
		{
			MethodName: "SetTopicArticles",
			Handler:    _ArticleService_SetTopicArticles_Handler,
		},
		{
			MethodName: "GetTrendingArticles",
			Handler:    _ArticleService_GetTrendingArticles_Handler,
		},
		{
			MethodName: "SetTrendingArticles",
			Handler:    _ArticleService_SetTrendingArticles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/article/article.proto",
}
