# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interest/interest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17interest/interest.proto\x1a\x1bgoogle/protobuf/empty.proto\".\n\x0e\x43reateInterest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06userId\x18\x02 \x01(\x04\"4\n\x08Interest\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06userId\x18\x03 \x01(\x04\"0\n\x10InterestResponse\x12\x1c\n\tinterests\x18\x01 \x03(\x0b\x32\t.Interest\"%\n\x13GetInterestsRequest\x12\x0e\n\x06userId\x18\x01 \x01(\x04\"I\n\x13\x41\x64\x64InterestsRequest\x12\"\n\tinterests\x18\x01 \x03(\x0b\x32\x0f.CreateInterest\x12\x0e\n\x06userId\x18\x02 \x01(\x04\"%\n\x16\x44\x65leteInterestsRequest\x12\x0b\n\x03ids\x18\x01 \x03(\x04\x32\xc7\x01\n\x0fInterestService\x12\x37\n\x0c\x41\x64\x64Interests\x12\x14.AddInterestsRequest\x1a\x11.InterestResponse\x12\x42\n\x0f\x44\x65leteInterests\x12\x17.DeleteInterestsRequest\x1a\x16.google.protobuf.Empty\x12\x37\n\x0cGetInterests\x12\x14.GetInterestsRequest\x1a\x11.InterestResponseB\x10Z\x0eproto/interestb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'interest.interest_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\016proto/interest'
  _CREATEINTEREST._serialized_start=56
  _CREATEINTEREST._serialized_end=102
  _INTEREST._serialized_start=104
  _INTEREST._serialized_end=156
  _INTERESTRESPONSE._serialized_start=158
  _INTERESTRESPONSE._serialized_end=206
  _GETINTERESTSREQUEST._serialized_start=208
  _GETINTERESTSREQUEST._serialized_end=245
  _ADDINTERESTSREQUEST._serialized_start=247
  _ADDINTERESTSREQUEST._serialized_end=320
  _DELETEINTERESTSREQUEST._serialized_start=322
  _DELETEINTERESTSREQUEST._serialized_end=359
  _INTERESTSERVICE._serialized_start=362
  _INTERESTSERVICE._serialized_end=561
# @@protoc_insertion_point(module_scope)
