apiVersion: batch/v1
kind: CronJob
metadata:
  name: collector
spec:
  schedule: "{{ .Values.cron.schedule }}"
  successfulJobsHistoryLimit: {{ .Values.cron.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cron.failedJobsHistoryLimit }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.cron.backoffLimit }}
      template:
        spec:
          serviceAccountName: collector
          containers:
            - image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
              name: collector
              env:
                - name: BACKEND_URL
                  value: {{ .Values.backendUrl }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          restartPolicy: Never
